In [1]:
import os
# os.environ["CUDA_VISIBLE_DEVICES"] = "-1" 

import pandas as pd
import matplotlib.pyplot as plt
from mlxtend.frequent_patterns import apriori, association_rules
import numpy as np
import time

In [2]:
# a = pd.read_csv("./bikeshare/status_station_zip_code.csv")
# a

,station_id,bikes_available,docks_available,time,name,lat,long,dock_count,city,installation_date,zip_code
0,14,10,9,2015-07-26 16:49:00.000,Arena Green / SAP Center,37.332692,-121.900084,19,San Jose,2013-08-05 00:00:00.000,95113
1,14,10,9,2015-07-26 16:50:00.000,Arena Green / SAP Center,37.332692,-121.900084,19,San Jose,2013-08-05 00:00:00.000,95113
2,14,10,9,2015-07-26 16:51:00.000,Arena Green / SAP Center,37.332692,-121.900084,19,San Jose,2013-08-05 00:00:00.000,95113
3,14,10,9,2015-07-26 16:52:00.000,Arena Green / SAP Center,37.332692,-121.900084,19,San Jose,2013-08-05 00:00:00.000,95113
4,14,10,9,2015-07-26 16:53:00.000,Arena Green / SAP Center,37.332692,-121.900084,19,San Jose,2013-08-05 00:00:00.000,95113
...,...,...,...,...,...,...,...,...,...,...,...
71984429,58,3,16,2015-04-05 18:18:00.000,San Francisco City Hall,37.778650,-122.418235,19,San Francisco,2013-08-21 00:00:00.000,94107
71984430,58,3,16,2015-04-05 18:19:00.000,San Francisco City Hall,37.778650,-122.418235,19,San Francisco,2013-08-21 00:00:00.000,94107
71984431,58,3,16,2015-04-05 18:20:00.000,San Francisco City Hall,37.778650,-122.418235,19,San Francisco,2013-08-21 00:00:00.000,94107
71984432,58,3,16,2015-04-05 18:21:00.000,San Francisco City Hall,37.778650,-122.418235,19,San Francisco,2013-08-21 00:00:00.000,94107
71984433,58,3,16,2015-04-05 18:22:00.000,San Francisco City Hall,37.778650,-122.418235,19,San Francisco,2013-08-21 00:00:00.000,94107

In [2]:
rules = pd.read_csv("./bikeshare/trip_association_rules.csv")
rules

,Unnamed: 0,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,37,frozenset({65}),frozenset({69}),0.074536,0.102153,0.014495,0.194469,1.903711,0.006881,1.114603
1,29,frozenset({60}),frozenset({50}),0.084210,0.096116,0.014023,0.166528,1.732565,0.005929,1.084480
2,30,frozenset({61}),frozenset({50}),0.080129,0.096116,0.013726,0.171302,1.782235,0.006025,1.090727
3,34,frozenset({74}),frozenset({60}),0.073430,0.084210,0.011023,0.150117,1.782657,0.004840,1.077549
4,36,frozenset({64}),frozenset({77}),0.052099,0.077318,0.010529,0.202097,2.613838,0.006501,1.156384
5,31,frozenset({51}),frozenset({70}),0.040641,0.166783,0.010445,0.257015,1.541010,0.003667,1.121445
6,32,frozenset({39}),frozenset({69}),0.056215,0.102153,0.009392,0.167065,1.635446,0.003649,1.077932
7,38,frozenset({72}),frozenset({65}),0.041801,0.074536,0.008015,0.191751,2.572605,0.004900,1.145024
8,15,frozenset({27}),frozenset({28}),0.009062,0.019009,0.007563,0.834624,43.907625,0.007391,5.931871
9,16,frozenset({28}),frozenset({27}),0.019009,0.009062,0.007563,0.397880,43.907625,0.007391,1.645748
10,33,frozenset({57}),frozenset({69}),0.041756,0.102153,0.007071,0.169330,1.657617,0.002805,1.080871
11,35,frozenset({63}),frozenset({70}),0.040174,0.166783,0.006809,0.169497,1.016268,0.000109,1.003267
12,2,frozenset({4}),frozenset({2}),0.010998,0.028035,0.006691,0.608442,21.703287,0.006383,2.482302
13,1,frozenset({2}),frozenset({4}),0.028035,0.010998,0.006691,0.238686,21.703287,0.006383,1.299073
14,39,frozenset({68}),frozenset({70}),0.034424,0.166783,0.006256,0.181720,1.089555,0.000514,1.018253
15,19,frozenset({32}),frozenset({28}),0.005506,0.019009,0.004727,0.858498,45.163614,0.004622,6.932715
16,20,frozenset({28}),frozenset({32}),0.019009,0.005506,0.004727,0.248685,45.163614,0.004622,1.323670
17,23,frozenset({31}),frozenset({29}),0.005336,0.005868,0.003806,0.713287,121.565213,0.003775,3.467340
18,22,frozenset({29}),frozenset({31}),0.005868,0.005336,0.003806,0.648690,121.565213,0.003775,2.831299
19,4,frozenset({6}),frozenset({2}),0.008781,0.028035,0.003651,0.415774,14.830780,0.003405,1.663681
20,18,frozenset({30}),frozenset({28}),0.004264,0.019009,0.003611,0.846692,44.542532,0.003530,6.398841
21,17,frozenset({28}),frozenset({30}),0.019009,0.004264,0.003611,0.189949,44.542532,0.003530,1.229226
22,5,frozenset({7}),frozenset({2}),0.006839,0.028035,0.002540,0.371454,13.249847,0.002349,1.546370
23,8,frozenset({11}),frozenset({2}),0.006514,0.028035,0.002409,0.369844,13.192442,0.002226,1.542421
24,27,frozenset({37}),frozenset({34}),0.003605,0.005275,0.002166,0.600828,113.902159,0.002147,2.491972
25,26,frozenset({34}),frozenset({37}),0.005275,0.003605,0.002166,0.410583,113.902159,0.002147,1.690476
26,3,frozenset({5}),frozenset({2}),0.003505,0.028035,0.001961,0.559625,19.961982,0.001863,2.207132
27,9,frozenset({13}),frozenset({2}),0.004602,0.028035,0.001851,0.402206,14.346784,0.001722,1.625919
28,7,frozenset({10}),frozenset({2}),0.005705,0.028035,0.001843,0.323129,11.526107,0.001683,1.435969
29,12,frozenset({14}),frozenset({4}),0.003949,0.010998,0.001636,0.414210,37.663383,0.001592,1.688323
30,6,frozenset({9}),frozenset({2}),0.005791,0.028035,0.001600,0.276289,9.855291,0.001438,1.343029
31,11,frozenset({84}),frozenset({2}),0.004573,0.028035,0.001385,0.302872,10.803528,0.001257,1.394243
32,21,frozenset({33}),frozenset({28}),0.003075,0.019009,0.001237,0.402427,21.170767,0.001179,1.641627
33,0,frozenset({3}),frozenset({2}),0.004461,0.028035,0.001237,0.277350,9.893159,0.001112,1.345002
34,40,frozenset({80}),frozenset({84}),0.002470,0.004573,0.001233,0.499094,109.129336,0.001222,1.987251
35,41,frozenset({84}),frozenset({80}),0.004573,0.002470,0.001233,0.269582,109.129336,0.001222,1.365697
36,10,frozenset({16}),frozenset({2}),0.004242,0.028035,0.001197,0.282196,10.065994,0.001078,1.354081
37,13,frozenset({25}),frozenset({22}),0.001425,0.003961,0.001034,0.725654,183.179627,0.001029,3.630599
38,14,frozenset({22}),frozenset({25}),0.003961,0.001425,0.001034,0.261115,183.179627,0.001029,1.351462
39,25,frozenset({36}),frozenset({34}),0.002912,0.005275,0.001031,0.354177,67.143265,0.001016,1.540245
40,24,frozenset({34}),frozenset({36}),0.005275,0.002912,0.001031,0.195529,67.143265,0.001016,1.239433

In [10]:
rules = rules.drop("Unnamed: 0", axis=1)
for i in range(rules.shape[0]):
    rules.loc[i, "antecedents"] = int(rules.loc[i, "antecedents"][11:-2])
    rules.loc[i, "consequents"] = int(rules.loc[i, "consequents"][11:-2])
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,65,69,0.074536,0.102153,0.014495,0.194469,1.903711,0.006881,1.114603
1,60,50,0.084210,0.096116,0.014023,0.166528,1.732565,0.005929,1.084480
2,61,50,0.080129,0.096116,0.013726,0.171302,1.782235,0.006025,1.090727
3,74,60,0.073430,0.084210,0.011023,0.150117,1.782657,0.004840,1.077549
4,64,77,0.052099,0.077318,0.010529,0.202097,2.613838,0.006501,1.156384
5,51,70,0.040641,0.166783,0.010445,0.257015,1.541010,0.003667,1.121445
6,39,69,0.056215,0.102153,0.009392,0.167065,1.635446,0.003649,1.077932
7,72,65,0.041801,0.074536,0.008015,0.191751,2.572605,0.004900,1.145024
8,27,28,0.009062,0.019009,0.007563,0.834624,43.907625,0.007391,5.931871
9,28,27,0.019009,0.009062,0.007563,0.397880,43.907625,0.007391,1.645748
10,57,69,0.041756,0.102153,0.007071,0.169330,1.657617,0.002805,1.080871
11,63,70,0.040174,0.166783,0.006809,0.169497,1.016268,0.000109,1.003267
12,4,2,0.010998,0.028035,0.006691,0.608442,21.703287,0.006383,2.482302
13,2,4,0.028035,0.010998,0.006691,0.238686,21.703287,0.006383,1.299073
14,68,70,0.034424,0.166783,0.006256,0.181720,1.089555,0.000514,1.018253
15,32,28,0.005506,0.019009,0.004727,0.858498,45.163614,0.004622,6.932715
16,28,32,0.019009,0.005506,0.004727,0.248685,45.163614,0.004622,1.323670
17,31,29,0.005336,0.005868,0.003806,0.713287,121.565213,0.003775,3.467340
18,29,31,0.005868,0.005336,0.003806,0.648690,121.565213,0.003775,2.831299
19,6,2,0.008781,0.028035,0.003651,0.415774,14.830780,0.003405,1.663681
20,30,28,0.004264,0.019009,0.003611,0.846692,44.542532,0.003530,6.398841
21,28,30,0.019009,0.004264,0.003611,0.189949,44.542532,0.003530,1.229226
22,7,2,0.006839,0.028035,0.002540,0.371454,13.249847,0.002349,1.546370
23,11,2,0.006514,0.028035,0.002409,0.369844,13.192442,0.002226,1.542421
24,37,34,0.003605,0.005275,0.002166,0.600828,113.902159,0.002147,2.491972
25,34,37,0.005275,0.003605,0.002166,0.410583,113.902159,0.002147,1.690476
26,5,2,0.003505,0.028035,0.001961,0.559625,19.961982,0.001863,2.207132
27,13,2,0.004602,0.028035,0.001851,0.402206,14.346784,0.001722,1.625919
28,10,2,0.005705,0.028035,0.001843,0.323129,11.526107,0.001683,1.435969
29,14,4,0.003949,0.010998,0.001636,0.414210,37.663383,0.001592,1.688323
30,9,2,0.005791,0.028035,0.001600,0.276289,9.855291,0.001438,1.343029
31,84,2,0.004573,0.028035,0.001385,0.302872,10.803528,0.001257,1.394243
32,33,28,0.003075,0.019009,0.001237,0.402427,21.170767,0.001179,1.641627
33,3,2,0.004461,0.028035,0.001237,0.277350,9.893159,0.001112,1.345002
34,80,84,0.002470,0.004573,0.001233,0.499094,109.129336,0.001222,1.987251
35,84,80,0.004573,0.002470,0.001233,0.269582,109.129336,0.001222,1.365697
36,16,2,0.004242,0.028035,0.001197,0.282196,10.065994,0.001078,1.354081
37,25,22,0.001425,0.003961,0.001034,0.725654,183.179627,0.001029,3.630599
38,22,25,0.003961,0.001425,0.001034,0.261115,183.179627,0.001029,1.351462
39,36,34,0.002912,0.005275,0.001031,0.354177,67.143265,0.001016,1.540245
40,34,36,0.005275,0.002912,0.001031,0.195529,67.143265,0.001016,1.239433

In [11]:
rules.to_csv("./bikeshare/trip_association_rules.csv")

In [3]:
station = pd.read_csv("./bikeshare/station.csv")
station

,id,name,lat,long,dock_count,city,installation_date
0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,San Jose,8/6/2013
1,3,San Jose Civic Center,37.330698,-121.888979,15,San Jose,8/5/2013
2,4,Santa Clara at Almaden,37.333988,-121.894902,11,San Jose,8/6/2013
3,5,Adobe on Almaden,37.331415,-121.893200,19,San Jose,8/5/2013
4,6,San Pedro Square,37.336721,-121.894074,15,San Jose,8/7/2013
...,...,...,...,...,...,...,...
65,77,Market at Sansome,37.789625,-122.400811,27,San Francisco,8/25/2013
66,80,Santa Clara County Civic Center,37.352601,-121.905733,15,San Jose,12/31/2013
67,82,Broadway St at Battery St,37.798541,-122.400862,15,San Francisco,1/22/2014
68,83,Mezes Park,37.491269,-122.236234,15,Redwood City,2/20/2014
69,84,Ryland Park,37.342725,-121.895617,15,San Jose,4/9/2014

In [4]:
station.id.unique()

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 16, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 41, 42,
       45, 46, 47, 48, 49, 50, 51, 39, 54, 55, 56, 57, 58, 59, 60, 61, 62,
       63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 80, 82,
       83, 84], dtype=int64)

In [12]:
association = dict()
for i in station.id.unique():
    association[i] = [i]
for i in range(rules.shape[0]):
    association[rules.loc[i, 'antecedents']].append(rules.loc[i, 'consequents'])
association

{2: [2, 4],
 3: [3, 2],
 4: [4, 2],
 5: [5, 2],
 6: [6, 2],
 7: [7, 2],
 8: [8],
 9: [9, 2],
 10: [10, 2],
 11: [11, 2],
 12: [12],
 13: [13, 2],
 14: [14, 4],
 16: [16, 2],
 21: [21],
 22: [22, 25],
 23: [23],
 24: [24],
 25: [25, 22],
 26: [26],
 27: [27, 28],
 28: [28, 27, 32, 30],
 29: [29, 31],
 30: [30, 28],
 31: [31, 29],
 32: [32, 28],
 33: [33, 28],
 34: [34, 37, 36],
 35: [35],
 36: [36, 34],
 37: [37, 34],
 38: [38],
 41: [41],
 42: [42],
 45: [45],
 46: [46],
 47: [47],
 48: [48],
 49: [49],
 50: [50],
 51: [51, 70],
 39: [39, 69],
 54: [54],
 55: [55],
 56: [56],
 57: [57, 69],
 58: [58],
 59: [59],
 60: [60, 50],
 61: [61, 50],
 62: [62],
 63: [63, 70],
 64: [64, 77],
 65: [65, 69],
 66: [66],
 67: [67],
 68: [68, 70],
 69: [69],
 70: [70],
 71: [71],
 72: [72, 65],
 73: [73],
 74: [74, 60],
 75: [75],
 76: [76],
 77: [77],
 80: [80, 84],
 82: [82],
 83: [83],
 84: [84, 2, 80]}

In [13]:
city2zip = {'San Francisco':94107, 'Redwood City':94063, 'Palo Alto':94301, 'Mountain View':94041, 'San Jose':95113}
id2city = dict()
for i in range(station.shape[0]):
    id2city[station.loc[i, 'id']] = station.loc[i, 'city']
id2city

{2: 'San Jose',
 3: 'San Jose',
 4: 'San Jose',
 5: 'San Jose',
 6: 'San Jose',
 7: 'San Jose',
 8: 'San Jose',
 9: 'San Jose',
 10: 'San Jose',
 11: 'San Jose',
 12: 'San Jose',
 13: 'San Jose',
 14: 'San Jose',
 16: 'San Jose',
 21: 'Redwood City',
 22: 'Redwood City',
 23: 'Redwood City',
 24: 'Redwood City',
 25: 'Redwood City',
 26: 'Redwood City',
 27: 'Mountain View',
 28: 'Mountain View',
 29: 'Mountain View',
 30: 'Mountain View',
 31: 'Mountain View',
 32: 'Mountain View',
 33: 'Mountain View',
 34: 'Palo Alto',
 35: 'Palo Alto',
 36: 'Palo Alto',
 37: 'Palo Alto',
 38: 'Palo Alto',
 41: 'San Francisco',
 42: 'San Francisco',
 45: 'San Francisco',
 46: 'San Francisco',
 47: 'San Francisco',
 48: 'San Francisco',
 49: 'San Francisco',
 50: 'San Francisco',
 51: 'San Francisco',
 39: 'San Francisco',
 54: 'San Francisco',
 55: 'San Francisco',
 56: 'San Francisco',
 57: 'San Francisco',
 58: 'San Francisco',
 59: 'San Francisco',
 60: 'San Francisco',
 61: 'San Francisco',
 62: 'San Francisco',
 63: 'San Francisco',
 64: 'San Francisco',
 65: 'San Francisco',
 66: 'San Francisco',
 67: 'San Francisco',
 68: 'San Francisco',
 69: 'San Francisco',
 70: 'San Francisco',
 71: 'San Francisco',
 72: 'San Francisco',
 73: 'San Francisco',
 74: 'San Francisco',
 75: 'San Francisco',
 76: 'San Francisco',
 77: 'San Francisco',
 80: 'San Jose',
 82: 'San Francisco',
 83: 'Redwood City',
 84: 'San Jose'}

In [14]:
status = pd.read_csv("./bikeshare/status.csv")
status['city_zip'] = ''
status.loc[:, 'city_zip'] = status.loc[:, 'station_id'].apply(lambda x: city2zip[id2city[x]])
# station.loc[station['id'] == x, 'city'].values[0]
status

,station_id,bikes_available,docks_available,time,city_zip
0,2,2,25,2013/08/29 12:06:01,95113
1,2,2,25,2013/08/29 12:07:01,95113
2,2,2,25,2013/08/29 12:08:01,95113
3,2,2,25,2013/08/29 12:09:01,95113
4,2,2,25,2013/08/29 12:10:01,95113
...,...,...,...,...,...
71984429,84,8,7,2015-08-31 23:55:02,95113
71984430,84,8,7,2015-08-31 23:56:01,95113
71984431,84,8,7,2015-08-31 23:57:02,95113
71984432,84,8,7,2015-08-31 23:58:02,95113
71984433,84,8,7,2015-08-31 23:59:02,95113

In [15]:
trip = pd.read_csv("./bikeshare/trip.csv")
trip

,id,duration,start_date,start_station_name,start_station_id,end_date,end_station_name,end_station_id,bike_id,subscription_type,zip_code
0,4576,63,8/29/2013 14:13,South Van Ness at Market,66,8/29/2013 14:14,South Van Ness at Market,66,520,Subscriber,94127
1,4607,70,8/29/2013 14:42,San Jose City Hall,10,8/29/2013 14:43,San Jose City Hall,10,661,Subscriber,95138
2,4130,71,8/29/2013 10:16,Mountain View City Hall,27,8/29/2013 10:17,Mountain View City Hall,27,48,Subscriber,97214
3,4251,77,8/29/2013 11:29,San Jose City Hall,10,8/29/2013 11:30,San Jose City Hall,10,26,Subscriber,95060
4,4299,83,8/29/2013 12:02,South Van Ness at Market,66,8/29/2013 12:04,Market at 10th,67,319,Subscriber,94103
...,...,...,...,...,...,...,...,...,...,...,...
669954,432951,619,9/1/2014 4:21,Powell Street BART,39,9/1/2014 4:32,Townsend at 7th,65,335,Subscriber,94118
669955,432950,6712,9/1/2014 3:16,Harry Bridges Plaza (Ferry Building),50,9/1/2014 5:08,San Francisco Caltrain (Townsend at 4th),70,259,Customer,44100
669956,432949,538,9/1/2014 0:05,South Van Ness at Market,66,9/1/2014 0:14,5th at Howard,57,466,Customer,32
669957,432948,568,9/1/2014 0:05,South Van Ness at Market,66,9/1/2014 0:15,5th at Howard,57,461,Customer,32
669958,432947,569,9/1/2014 0:05,South Van Ness at Market,66,9/1/2014 0:15,5th at Howard,57,318,Customer,32

In [16]:
weather = pd.read_csv("./bikeshare/weather.csv")
weather.date = weather.date.apply(lambda x: x.split("/")[2] + "-" + x.split("/")[0] + "-" + x.split("/")[1])
weather.date = pd.to_datetime(weather.date).dt.strftime('%Y/%m/%d')
weather

,date,max_temperature_f,mean_temperature_f,min_temperature_f,max_dew_point_f,mean_dew_point_f,min_dew_point_f,max_humidity,mean_humidity,min_humidity,...,mean_visibility_miles,min_visibility_miles,max_wind_Speed_mph,mean_wind_speed_mph,max_gust_speed_mph,precipitation_inches,cloud_cover,events,wind_dir_degrees,zip_code
0,2013/08/29,74.0,68.0,61.0,61.0,58.0,56.0,93.0,75.0,57.0,...,10.0,10.0,23.0,11.0,28.0,0,4.0,NaN,286.0,94107
1,2013/08/30,78.0,69.0,60.0,61.0,58.0,56.0,90.0,70.0,50.0,...,10.0,7.0,29.0,13.0,35.0,0,2.0,NaN,291.0,94107
2,2013/08/31,71.0,64.0,57.0,57.0,56.0,54.0,93.0,75.0,57.0,...,10.0,10.0,26.0,15.0,31.0,0,4.0,NaN,284.0,94107
3,2013/09/01,74.0,66.0,58.0,60.0,56.0,53.0,87.0,68.0,49.0,...,10.0,10.0,25.0,13.0,29.0,0,4.0,NaN,284.0,94107
4,2013/09/02,75.0,69.0,62.0,61.0,60.0,58.0,93.0,77.0,61.0,...,10.0,6.0,23.0,12.0,30.0,0,6.0,NaN,277.0,94107
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3660,2015/08/27,92.0,78.0,63.0,57.0,51.0,40.0,78.0,48.0,18.0,...,10.0,10.0,23.0,6.0,29.0,0,3.0,NaN,313.0,95113
3661,2015/08/28,95.0,80.0,64.0,64.0,56.0,52.0,93.0,60.0,26.0,...,10.0,10.0,25.0,7.0,30.0,0,3.0,NaN,307.0,95113
3662,2015/08/29,80.0,72.0,64.0,65.0,62.0,54.0,93.0,70.0,47.0,...,10.0,10.0,21.0,9.0,26.0,0,4.0,NaN,312.0,95113
3663,2015/08/30,78.0,70.0,62.0,60.0,57.0,53.0,84.0,64.0,43.0,...,10.0,10.0,22.0,10.0,29.0,0,3.0,NaN,291.0,95113
3664,2015/08/31,85.0,72.0,59.0,59.0,55.0,51.0,84.0,58.0,32.0,...,10.0,10.0,20.0,6.0,24.0,0,1.0,NaN,308.0,95113

In [17]:
weather.precipitation_inches.unique()

array(['0', '0.23', 'T', '0.01', '0.28', '0.63', '0.29', '0.06', '0.85',
       '0.09', '0.64', '0.42', '0.35', '0.43', '0.22', '0.74', '0.03',
       '0.12', '0.16', '0.49', '0.17', '0.08', '0.04', '0.53', '0.07',
       '0.02', '0.83', '1.06', '1.71', '0.37', '0.27', '0.45', '0.78',
       '0.88', '0.66', '0.47', '0.1', '0.61', '0.14', '0.05', '0.68',
       '0.97', '0.26', '0.15', '0.87', '0.57', '0.69', '0.32', '0.21',
       '0.24', '0.52', '0.36', '0.33', '0.25', '0.11', '0.2', '1.18',
       '1.43', '3.12', '0.48', '0.19', '1.09', '0.65', '0.13', '0.91',
       '0.99', '0.18', '0.4', '1.07', nan, '0.41', '0.34', '1.25', '1.85',
       '3.36', '0.71', '1.3', '0.72', '0.6', '0.51', '1.2', '1.28',
       '3.23', '0.55', '1.26', '0.39'], dtype=object)

In [18]:
weather.dtypes

date                               object
max_temperature_f                 float64
mean_temperature_f                float64
min_temperature_f                 float64
max_dew_point_f                   float64
mean_dew_point_f                  float64
min_dew_point_f                   float64
max_humidity                      float64
mean_humidity                     float64
min_humidity                      float64
max_sea_level_pressure_inches     float64
mean_sea_level_pressure_inches    float64
min_sea_level_pressure_inches     float64
max_visibility_miles              float64
mean_visibility_miles             float64
min_visibility_miles              float64
max_wind_Speed_mph                float64
mean_wind_speed_mph               float64
max_gust_speed_mph                float64
precipitation_inches               object
cloud_cover                       float64
events                             object
wind_dir_degrees                  float64
zip_code                            int64
dtype: object

In [19]:
weather.events = weather.events.apply(lambda x: 0 if type(x) == np.float else 1) # nan <-- np.float
weather.precipitation_inches = weather.precipitation_inches.apply(lambda x: 0.0 if x == 'T' else x)
weather.precipitation_inches = weather.precipitation_inches.astype(np.float)
weather.fillna(method='ffill', inplace=True)
weather

,date,max_temperature_f,mean_temperature_f,min_temperature_f,max_dew_point_f,mean_dew_point_f,min_dew_point_f,max_humidity,mean_humidity,min_humidity,...,mean_visibility_miles,min_visibility_miles,max_wind_Speed_mph,mean_wind_speed_mph,max_gust_speed_mph,precipitation_inches,cloud_cover,events,wind_dir_degrees,zip_code
0,2013/08/29,74.0,68.0,61.0,61.0,58.0,56.0,93.0,75.0,57.0,...,10.0,10.0,23.0,11.0,28.0,0.0,4.0,0,286.0,94107
1,2013/08/30,78.0,69.0,60.0,61.0,58.0,56.0,90.0,70.0,50.0,...,10.0,7.0,29.0,13.0,35.0,0.0,2.0,0,291.0,94107
2,2013/08/31,71.0,64.0,57.0,57.0,56.0,54.0,93.0,75.0,57.0,...,10.0,10.0,26.0,15.0,31.0,0.0,4.0,0,284.0,94107
3,2013/09/01,74.0,66.0,58.0,60.0,56.0,53.0,87.0,68.0,49.0,...,10.0,10.0,25.0,13.0,29.0,0.0,4.0,0,284.0,94107
4,2013/09/02,75.0,69.0,62.0,61.0,60.0,58.0,93.0,77.0,61.0,...,10.0,6.0,23.0,12.0,30.0,0.0,6.0,0,277.0,94107
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3660,2015/08/27,92.0,78.0,63.0,57.0,51.0,40.0,78.0,48.0,18.0,...,10.0,10.0,23.0,6.0,29.0,0.0,3.0,0,313.0,95113
3661,2015/08/28,95.0,80.0,64.0,64.0,56.0,52.0,93.0,60.0,26.0,...,10.0,10.0,25.0,7.0,30.0,0.0,3.0,0,307.0,95113
3662,2015/08/29,80.0,72.0,64.0,65.0,62.0,54.0,93.0,70.0,47.0,...,10.0,10.0,21.0,9.0,26.0,0.0,4.0,0,312.0,95113
3663,2015/08/30,78.0,70.0,62.0,60.0,57.0,53.0,84.0,64.0,43.0,...,10.0,10.0,22.0,10.0,29.0,0.0,3.0,0,291.0,95113
3664,2015/08/31,85.0,72.0,59.0,59.0,55.0,51.0,84.0,58.0,32.0,...,10.0,10.0,20.0,6.0,24.0,0.0,1.0,0,308.0,95113

In [20]:
weather.isna().any()

date                              False
max_temperature_f                 False
mean_temperature_f                False
min_temperature_f                 False
max_dew_point_f                   False
mean_dew_point_f                  False
min_dew_point_f                   False
max_humidity                      False
mean_humidity                     False
min_humidity                      False
max_sea_level_pressure_inches     False
mean_sea_level_pressure_inches    False
min_sea_level_pressure_inches     False
max_visibility_miles              False
mean_visibility_miles             False
min_visibility_miles              False
max_wind_Speed_mph                False
mean_wind_speed_mph               False
max_gust_speed_mph                False
precipitation_inches              False
cloud_cover                       False
events                            False
wind_dir_degrees                  False
zip_code                          False
dtype: bool

In [22]:
status2 = status.loc[status['station_id']==2, :]
status2

,station_id,bikes_available,docks_available,time,city_zip
0,2,2,25,2013/08/29 12:06:01,95113
1,2,2,25,2013/08/29 12:07:01,95113
2,2,2,25,2013/08/29 12:08:01,95113
3,2,2,25,2013/08/29 12:09:01,95113
4,2,2,25,2013/08/29 12:10:01,95113
...,...,...,...,...,...
35860185,2,18,9,2015-08-31 23:55:02,95113
35860186,2,18,9,2015-08-31 23:56:01,95113
35860187,2,18,9,2015-08-31 23:57:02,95113
35860188,2,18,9,2015-08-31 23:58:02,95113
35860189,2,18,9,2015-08-31 23:59:02,95113

In [23]:
# 注意時間的格式(避免無法merge)
# The day of the week with Monday=0, Sunday=6.
status2.loc[:, 'month'] = pd.to_datetime(status2.time, format='%Y-%m-%d %H:%M:%S').dt.month
status2.loc[:, 'dayofweek'] = pd.to_datetime(status2.time, format='%Y-%m-%d %H:%M:%S').dt.dayofweek
status2.loc[:, 'hour'] = pd.to_datetime(status2.time, format='%Y-%m-%d %H:%M:%S').dt.hour
status2.loc[:, 'time'] = pd.to_datetime(status2['time'].str[:10]).dt.strftime('%Y/%m/%d')
# s2['time'] = s2['time'].str[:10]
# s2 = s2.drop('time', axis=1)
status2

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

,station_id,bikes_available,docks_available,time,city_zip,month,dayofweek,hour
0,2,2,25,2013/08/29,95113,8,3,12
1,2,2,25,2013/08/29,95113,8,3,12
2,2,2,25,2013/08/29,95113,8,3,12
3,2,2,25,2013/08/29,95113,8,3,12
4,2,2,25,2013/08/29,95113,8,3,12
...,...,...,...,...,...,...,...,...
35860185,2,18,9,2015/08/31,95113,8,0,23
35860186,2,18,9,2015/08/31,95113,8,0,23
35860187,2,18,9,2015/08/31,95113,8,0,23
35860188,2,18,9,2015/08/31,95113,8,0,23
35860189,2,18,9,2015/08/31,95113,8,0,23

In [24]:
status2 = status2.groupby(['time', 'hour']).mean()
status2.reset_index(inplace=True, level=['time', 'hour'])
status2

,time,hour,station_id,bikes_available,docks_available,city_zip,month,dayofweek
0,2013/08/29,12,2.0,2.000000,25.000000,95113.0,8.0,3.0
1,2013/08/29,13,2.0,2.698113,24.301887,95113.0,8.0,3.0
2,2013/08/29,14,2.0,2.000000,25.000000,95113.0,8.0,3.0
3,2013/08/29,15,2.0,2.000000,25.000000,95113.0,8.0,3.0
4,2013/08/29,16,2.0,2.000000,25.000000,95113.0,8.0,3.0
...,...,...,...,...,...,...,...,...
17522,2015/08/31,19,2.0,17.900000,9.100000,95113.0,8.0,0.0
17523,2015/08/31,20,2.0,18.000000,9.000000,95113.0,8.0,0.0
17524,2015/08/31,21,2.0,18.000000,9.000000,95113.0,8.0,0.0
17525,2015/08/31,22,2.0,18.000000,9.000000,95113.0,8.0,0.0
17526,2015/08/31,23,2.0,18.000000,9.000000,95113.0,8.0,0.0

In [28]:
status2_X = pd.merge(status2, weather[weather['zip_code'] == status2.city_zip.unique()[0]], left_on=['time', 'city_zip'], right_on=['date', 'zip_code'])
status2_X = status2_X.drop(['date', 'zip_code'], axis=1)
status2_X

,time,hour,station_id,bikes_available,docks_available,city_zip,month,dayofweek,max_temperature_f,mean_temperature_f,...,max_visibility_miles,mean_visibility_miles,min_visibility_miles,max_wind_Speed_mph,mean_wind_speed_mph,max_gust_speed_mph,precipitation_inches,cloud_cover,events,wind_dir_degrees
0,2013/08/29,12,2.0,2.000000,25.000000,95113.0,8.0,3.0,81.0,72.0,...,10.0,10.0,10.0,16.0,7.0,24.0,0,4.0,0,320.0
1,2013/08/29,13,2.0,2.698113,24.301887,95113.0,8.0,3.0,81.0,72.0,...,10.0,10.0,10.0,16.0,7.0,24.0,0,4.0,0,320.0
2,2013/08/29,14,2.0,2.000000,25.000000,95113.0,8.0,3.0,81.0,72.0,...,10.0,10.0,10.0,16.0,7.0,24.0,0,4.0,0,320.0
3,2013/08/29,15,2.0,2.000000,25.000000,95113.0,8.0,3.0,81.0,72.0,...,10.0,10.0,10.0,16.0,7.0,24.0,0,4.0,0,320.0
4,2013/08/29,16,2.0,2.000000,25.000000,95113.0,8.0,3.0,81.0,72.0,...,10.0,10.0,10.0,16.0,7.0,24.0,0,4.0,0,320.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17522,2015/08/31,19,2.0,17.900000,9.100000,95113.0,8.0,0.0,85.0,72.0,...,10.0,10.0,10.0,20.0,6.0,24.0,0,1.0,0,308.0
17523,2015/08/31,20,2.0,18.000000,9.000000,95113.0,8.0,0.0,85.0,72.0,...,10.0,10.0,10.0,20.0,6.0,24.0,0,1.0,0,308.0
17524,2015/08/31,21,2.0,18.000000,9.000000,95113.0,8.0,0.0,85.0,72.0,...,10.0,10.0,10.0,20.0,6.0,24.0,0,1.0,0,308.0
17525,2015/08/31,22,2.0,18.000000,9.000000,95113.0,8.0,0.0,85.0,72.0,...,10.0,10.0,10.0,20.0,6.0,24.0,0,1.0,0,308.0
17526,2015/08/31,23,2.0,18.000000,9.000000,95113.0,8.0,0.0,85.0,72.0,...,10.0,10.0,10.0,20.0,6.0,24.0,0,1.0,0,308.0

In [32]:
weather[(weather['date']=='2015/08/31') & (weather['zip_code']==95113)]

,date,max_temperature_f,mean_temperature_f,min_temperature_f,max_dew_point_f,mean_dew_point_f,min_dew_point_f,max_humidity,mean_humidity,min_humidity,...,mean_visibility_miles,min_visibility_miles,max_wind_Speed_mph,mean_wind_speed_mph,max_gust_speed_mph,precipitation_inches,cloud_cover,events,wind_dir_degrees,zip_code
3664,2015/08/31,85.0,72.0,59.0,59.0,55.0,51.0,84.0,58.0,32.0,...,10.0,10.0,20.0,6.0,24.0,0,1.0,0,308.0,95113

In [24]:
weather.loc[(weather['date']=='2015/08/32') & (weather['zip_code']==95113), 'date'] # date, hour-1, station_id --> bike_ava

Series([], Name: date, dtype: object)

In [26]:
status2_X.isna().any()

time                              False
hour                              False
station_id                        False
bikes_available                   False
docks_available                   False
city_zip                          False
month                             False
dayofweek                         False
date                              False
max_temperature_f                 False
mean_temperature_f                False
min_temperature_f                 False
max_dew_point_f                   False
mean_dew_point_f                  False
min_dew_point_f                   False
max_humidity                      False
mean_humidity                     False
min_humidity                      False
max_sea_level_pressure_inches     False
mean_sea_level_pressure_inches    False
min_sea_level_pressure_inches     False
max_visibility_miles              False
mean_visibility_miles             False
min_visibility_miles              False
max_wind_Speed_mph                False
mean_wind_speed_mph               False
max_gust_speed_mph                False
precipitation_inches              False
cloud_cover                       False
events                            False
wind_dir_degrees                  False
zip_code                          False
dtype: bool

In [25]:
status.station_id.unique()

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 16, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 41, 42,
       45, 46, 47, 48, 49, 50, 51, 39, 54, 55, 56, 57, 58, 59, 60, 61, 62,
       63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 80, 82,
       83, 84], dtype=int64)

In [84]:
bikeshare_preprocessing = pd.DataFrame()
status_data = dict()
for i in status.station_id.unique():
    status_i = status.loc[status['station_id']==i, :]
    
    status_i.loc[:, 'month'] = pd.to_datetime(status_i.time, format='%Y-%m-%d %H:%M:%S').dt.month
    status_i.loc[:, 'dayofweek'] = pd.to_datetime(status_i.time, format='%Y-%m-%d %H:%M:%S').dt.dayofweek
    status_i.loc[:, 'hour'] = pd.to_datetime(status_i.time, format='%Y-%m-%d %H:%M:%S').dt.hour
    status_i.loc[:, 'time'] = pd.to_datetime(status_i['time'].str[:10]).dt.strftime('%Y/%m/%d')
    status_i = status_i.groupby(['time', 'hour']).mean()
    status_i.reset_index(inplace=True, level=['time', 'hour'])
    status_i['dock_count'] = station.loc[station.id == i, 'dock_count'].values[0]

    status_i = pd.merge(status_i, weather[weather['zip_code'] == status_i.city_zip.unique()[0]], left_on=['time', 'city_zip'], right_on=['date', 'zip_code'])
    status_i = status_i.drop(['date', 'zip_code'], axis=1)
    
    status_data[i] = status_i
    bikeshare_preprocessing = bikeshare_preprocessing.append(status_i)
    print(f"station {i} done, shape: {status_i.shape}")
    print(status_i.loc[0, ['time', 'hour']])

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 2 done, shape: (17527, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 3 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 4 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 5 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 6 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 7 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 8 done, shape: (17522, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 9 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 10 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 11 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 12 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 13 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 14 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 16 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 21 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 22 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 23 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 24 done, shape: (17528, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 25 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 26 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 27 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 28 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 29 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 30 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 31 done, shape: (14558, 31)
time    2013/12/31
hour             8
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 32 done, shape: (14560, 31)
time    2013/12/31
hour             6
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 33 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 34 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 35 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 36 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 37 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 38 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 41 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 42 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 45 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 46 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 47 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 48 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 49 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 50 done, shape: (17528, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 51 done, shape: (17484, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 39 done, shape: (17528, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 54 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 55 done, shape: (17514, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 56 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 57 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 58 done, shape: (17496, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 59 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 60 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 61 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 62 done, shape: (17497, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 63 done, shape: (17452, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 64 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 65 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 66 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 67 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 68 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 69 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 70 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 71 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 72 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 73 done, shape: (17425, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 74 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 75 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 76 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 77 done, shape: (17530, 31)
time    2013/08/29
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 80 done, shape: (14556, 31)
time    2013/12/31
hour            10
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 82 done, shape: (14033, 31)
time    2014/01/22
hour             5
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 83 done, shape: (13330, 31)
time    2014/02/20
hour            12
Name: 0, dtype: object

c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
c:\users\oplab\anaconda3\envs\mds\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

station 84 done, shape: (12206, 31)
time    2014/04/09
hour            12
Name: 0, dtype: object

In [85]:
bikeshare_preprocessing.reset_index(inplace=True)
bikeshare_preprocessing = bikeshare_preprocessing.drop("index", axis=1)
bikeshare_preprocessing

,time,hour,station_id,bikes_available,docks_available,city_zip,month,dayofweek,dock_count,max_temperature_f,...,max_visibility_miles,mean_visibility_miles,min_visibility_miles,max_wind_Speed_mph,mean_wind_speed_mph,max_gust_speed_mph,precipitation_inches,cloud_cover,events,wind_dir_degrees
0,2013/08/29,12,2.0,2.000000,25.000000,95113.0,8.0,3.0,27,81.0,...,10.0,10.0,10.0,16.0,7.0,24.0,0.0,4.0,0,320.0
1,2013/08/29,13,2.0,2.698113,24.301887,95113.0,8.0,3.0,27,81.0,...,10.0,10.0,10.0,16.0,7.0,24.0,0.0,4.0,0,320.0
2,2013/08/29,14,2.0,2.000000,25.000000,95113.0,8.0,3.0,27,81.0,...,10.0,10.0,10.0,16.0,7.0,24.0,0.0,4.0,0,320.0
3,2013/08/29,15,2.0,2.000000,25.000000,95113.0,8.0,3.0,27,81.0,...,10.0,10.0,10.0,16.0,7.0,24.0,0.0,4.0,0,320.0
4,2013/08/29,16,2.0,2.000000,25.000000,95113.0,8.0,3.0,27,81.0,...,10.0,10.0,10.0,16.0,7.0,24.0,0.0,4.0,0,320.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1204829,2015/08/31,19,84.0,8.000000,7.000000,95113.0,8.0,0.0,15,85.0,...,10.0,10.0,10.0,20.0,6.0,24.0,0.0,1.0,0,308.0
1204830,2015/08/31,20,84.0,8.000000,7.000000,95113.0,8.0,0.0,15,85.0,...,10.0,10.0,10.0,20.0,6.0,24.0,0.0,1.0,0,308.0
1204831,2015/08/31,21,84.0,8.000000,7.000000,95113.0,8.0,0.0,15,85.0,...,10.0,10.0,10.0,20.0,6.0,24.0,0.0,1.0,0,308.0
1204832,2015/08/31,22,84.0,8.000000,7.000000,95113.0,8.0,0.0,15,85.0,...,10.0,10.0,10.0,20.0,6.0,24.0,0.0,1.0,0,308.0
1204833,2015/08/31,23,84.0,8.000000,7.000000,95113.0,8.0,0.0,15,85.0,...,10.0,10.0,10.0,20.0,6.0,24.0,0.0,1.0,0,308.0

In [101]:
bikeshare_preprocessing[bikeshare_preprocessing['station_id']==8]

,time,hour,station_id,bikes_available,docks_available,city_zip,month,dayofweek,dock_count,max_temperature_f,...,max_visibility_miles,mean_visibility_miles,min_visibility_miles,max_wind_Speed_mph,mean_wind_speed_mph,max_gust_speed_mph,precipitation_inches,cloud_cover,events,wind_dir_degrees
105177,2013/08/29,12,8.0,8.062500,6.937500,95113.0,8.0,3.0,15,81.0,...,10.0,10.0,10.0,16.0,7.0,24.0,0.0,4.0,0,320.0
105178,2013/08/29,13,8.0,8.981132,6.018868,95113.0,8.0,3.0,15,81.0,...,10.0,10.0,10.0,16.0,7.0,24.0,0.0,4.0,0,320.0
105179,2013/08/29,14,8.0,8.089286,6.910714,95113.0,8.0,3.0,15,81.0,...,10.0,10.0,10.0,16.0,7.0,24.0,0.0,4.0,0,320.0
105180,2013/08/29,15,8.0,8.000000,7.000000,95113.0,8.0,3.0,15,81.0,...,10.0,10.0,10.0,16.0,7.0,24.0,0.0,4.0,0,320.0
105181,2013/08/29,16,8.0,7.545455,7.454545,95113.0,8.0,3.0,15,81.0,...,10.0,10.0,10.0,16.0,7.0,24.0,0.0,4.0,0,320.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122694,2015/08/31,19,8.0,12.000000,3.000000,95113.0,8.0,0.0,15,85.0,...,10.0,10.0,10.0,20.0,6.0,24.0,0.0,1.0,0,308.0
122695,2015/08/31,20,8.0,12.000000,3.000000,95113.0,8.0,0.0,15,85.0,...,10.0,10.0,10.0,20.0,6.0,24.0,0.0,1.0,0,308.0
122696,2015/08/31,21,8.0,12.000000,3.000000,95113.0,8.0,0.0,15,85.0,...,10.0,10.0,10.0,20.0,6.0,24.0,0.0,1.0,0,308.0
122697,2015/08/31,22,8.0,12.000000,3.000000,95113.0,8.0,0.0,15,85.0,...,10.0,10.0,10.0,20.0,6.0,24.0,0.0,1.0,0,308.0
122698,2015/08/31,23,8.0,12.700000,2.300000,95113.0,8.0,0.0,15,85.0,...,10.0,10.0,10.0,20.0,6.0,24.0,0.0,1.0,0,308.0

In [86]:
bikeshare_preprocessing.to_csv("./bikeshare/bikeshare_preprocessing.csv")

In [ ]:
# != 17530
# 2 8 24 31 32 39 50 51 55 58 62 63 73 80 82 83 84

Add Association Rules

In [80]:
a = bikeshare_preprocessing[bikeshare_preprocessing.station_id == 3]
b = a[(a.time == "2013/08/29") & (a.hour == 12)].index.values
a.index[0]

17527

In [90]:
status_data[3]

,time,hour,station_id,bikes_available,docks_available,city_zip,month,dayofweek,dock_count,max_temperature_f,...,max_visibility_miles,mean_visibility_miles,min_visibility_miles,max_wind_Speed_mph,mean_wind_speed_mph,max_gust_speed_mph,precipitation_inches,cloud_cover,events,wind_dir_degrees
0,2013/08/29,12,3.0,8.083333,6.916667,95113.0,8.0,3.0,15,81.0,...,10.0,10.0,10.0,16.0,7.0,24.0,0.0,4.0,0,320.0
1,2013/08/29,13,3.0,9.000000,6.000000,95113.0,8.0,3.0,15,81.0,...,10.0,10.0,10.0,16.0,7.0,24.0,0.0,4.0,0,320.0
2,2013/08/29,14,3.0,9.000000,6.000000,95113.0,8.0,3.0,15,81.0,...,10.0,10.0,10.0,16.0,7.0,24.0,0.0,4.0,0,320.0
3,2013/08/29,15,3.0,9.000000,6.000000,95113.0,8.0,3.0,15,81.0,...,10.0,10.0,10.0,16.0,7.0,24.0,0.0,4.0,0,320.0
4,2013/08/29,16,3.0,9.381818,5.618182,95113.0,8.0,3.0,15,81.0,...,10.0,10.0,10.0,16.0,7.0,24.0,0.0,4.0,0,320.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17525,2015/08/31,19,3.0,7.000000,8.000000,95113.0,8.0,0.0,15,85.0,...,10.0,10.0,10.0,20.0,6.0,24.0,0.0,1.0,0,308.0
17526,2015/08/31,20,3.0,7.000000,8.000000,95113.0,8.0,0.0,15,85.0,...,10.0,10.0,10.0,20.0,6.0,24.0,0.0,1.0,0,308.0
17527,2015/08/31,21,3.0,7.000000,8.000000,95113.0,8.0,0.0,15,85.0,...,10.0,10.0,10.0,20.0,6.0,24.0,0.0,1.0,0,308.0
17528,2015/08/31,22,3.0,7.000000,8.000000,95113.0,8.0,0.0,15,85.0,...,10.0,10.0,10.0,20.0,6.0,24.0,0.0,1.0,0,308.0
17529,2015/08/31,23,3.0,7.000000,8.000000,95113.0,8.0,0.0,15,85.0,...,10.0,10.0,10.0,20.0,6.0,24.0,0.0,1.0,0,308.0

In [91]:
### Generate dataset ###
bikeshare_preprocessing_rules = pd.DataFrame()
first_record = []
for i in status_data:
    print(i)
    si = status_data[i]
    si['association_station'] = ''
    for j in range(len(si.index)):
        idx = si.index[j]
        if j == 0:
            first_record.append(idx)
            continue
        [t, h] = si.loc[idx, ['time', 'hour']].values
        association_station = association[k] # by rules
        as_count = []
        for as_id in association_station:
            s_as = status_data[as_id]
            as_idx = s_as[(s_as.time == t)&(s_as.hour == h)].index.values
            if len(as_idx) == 0:
                continue
            elif (as_idx[0] - 1) < s_as.index[0]:
                continue
            else:
                as_idx = as_idx[0] - 1
            as_count.append(s_as.loc[as_idx, 'bikes_available']/s_as.loc[as_idx, 'dock_count'])
        si.loc[idx, 'association_station'] = np.mean(as_count)
    bikeshare_preprocessing_rules = bikeshare_preprocessing_rules.append(si)
print("done")

2
3
4
5
6
7
8
9
10
11
12
13
14
16
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
41
42
45
46
47
48
49
50
51
39
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
80
82
83
84
done

In [96]:
# bikeshare_preprocessing_rules = pd.DataFrame()
# for k in status_data:
#     bikeshare_preprocessing_rules = bikeshare_preprocessing_rules.append(status_data[k])
# print("done")

done

In [97]:
bikeshare_preprocessing_rules

,time,hour,station_id,bikes_available,docks_available,city_zip,month,dayofweek,dock_count,max_temperature_f,...,mean_visibility_miles,min_visibility_miles,max_wind_Speed_mph,mean_wind_speed_mph,max_gust_speed_mph,precipitation_inches,cloud_cover,events,wind_dir_degrees,association_station
0,2013/08/29,12,2.0,2.000000,25.000000,95113.0,8.0,3.0,27,81.0,...,10.0,10.0,16.0,7.0,24.0,0.0,4.0,0,320.0,
1,2013/08/29,13,2.0,2.698113,24.301887,95113.0,8.0,3.0,27,81.0,...,10.0,10.0,16.0,7.0,24.0,0.0,4.0,0,320.0,0.0740741
2,2013/08/29,14,2.0,2.000000,25.000000,95113.0,8.0,3.0,27,81.0,...,10.0,10.0,16.0,7.0,24.0,0.0,4.0,0,320.0,0.0999301
3,2013/08/29,15,2.0,2.000000,25.000000,95113.0,8.0,3.0,27,81.0,...,10.0,10.0,16.0,7.0,24.0,0.0,4.0,0,320.0,0.0740741
4,2013/08/29,16,2.0,2.000000,25.000000,95113.0,8.0,3.0,27,81.0,...,10.0,10.0,16.0,7.0,24.0,0.0,4.0,0,320.0,0.0740741
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12201,2015/08/31,19,84.0,8.000000,7.000000,95113.0,8.0,0.0,15,85.0,...,10.0,10.0,20.0,6.0,24.0,0.0,1.0,0,308.0,0.572469
12202,2015/08/31,20,84.0,8.000000,7.000000,95113.0,8.0,0.0,15,85.0,...,10.0,10.0,20.0,6.0,24.0,0.0,1.0,0,308.0,0.554321
12203,2015/08/31,21,84.0,8.000000,7.000000,95113.0,8.0,0.0,15,85.0,...,10.0,10.0,20.0,6.0,24.0,0.0,1.0,0,308.0,0.555556
12204,2015/08/31,22,84.0,8.000000,7.000000,95113.0,8.0,0.0,15,85.0,...,10.0,10.0,20.0,6.0,24.0,0.0,1.0,0,308.0,0.555556
12205,2015/08/31,23,84.0,8.000000,7.000000,95113.0,8.0,0.0,15,85.0,...,10.0,10.0,20.0,6.0,24.0,0.0,1.0,0,308.0,0.555556

In [99]:
bikeshare_preprocessing_rules = bikeshare_preprocessing_rules.drop(first_record)
bikeshare_preprocessing_rules.reset_index(inplace=True)
bikeshare_preprocessing_rules = bikeshare_preprocessing_rules.drop("index", axis=1)
bikeshare_preprocessing_rules

,time,hour,station_id,bikes_available,docks_available,city_zip,month,dayofweek,dock_count,max_temperature_f,...,mean_visibility_miles,min_visibility_miles,max_wind_Speed_mph,mean_wind_speed_mph,max_gust_speed_mph,precipitation_inches,cloud_cover,events,wind_dir_degrees,association_station
0,2013/08/29,13,2.0,2.698113,24.301887,95113.0,8.0,3.0,27,81.0,...,10.0,10.0,16.0,7.0,24.0,0.0,4.0,0,320.0,0.0740741
1,2013/08/29,14,2.0,2.000000,25.000000,95113.0,8.0,3.0,27,81.0,...,10.0,10.0,16.0,7.0,24.0,0.0,4.0,0,320.0,0.0999301
2,2013/08/29,15,2.0,2.000000,25.000000,95113.0,8.0,3.0,27,81.0,...,10.0,10.0,16.0,7.0,24.0,0.0,4.0,0,320.0,0.0740741
3,2013/08/29,16,2.0,2.000000,25.000000,95113.0,8.0,3.0,27,81.0,...,10.0,10.0,16.0,7.0,24.0,0.0,4.0,0,320.0,0.0740741
4,2013/08/29,17,2.0,2.907407,24.092593,95113.0,8.0,3.0,27,81.0,...,10.0,10.0,16.0,7.0,24.0,0.0,4.0,0,320.0,0.0740741
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1204759,2015/08/31,19,84.0,8.000000,7.000000,95113.0,8.0,0.0,15,85.0,...,10.0,10.0,20.0,6.0,24.0,0.0,1.0,0,308.0,0.572469
1204760,2015/08/31,20,84.0,8.000000,7.000000,95113.0,8.0,0.0,15,85.0,...,10.0,10.0,20.0,6.0,24.0,0.0,1.0,0,308.0,0.554321
1204761,2015/08/31,21,84.0,8.000000,7.000000,95113.0,8.0,0.0,15,85.0,...,10.0,10.0,20.0,6.0,24.0,0.0,1.0,0,308.0,0.555556
1204762,2015/08/31,22,84.0,8.000000,7.000000,95113.0,8.0,0.0,15,85.0,...,10.0,10.0,20.0,6.0,24.0,0.0,1.0,0,308.0,0.555556
1204763,2015/08/31,23,84.0,8.000000,7.000000,95113.0,8.0,0.0,15,85.0,...,10.0,10.0,20.0,6.0,24.0,0.0,1.0,0,308.0,0.555556

In [100]:
bikeshare_preprocessing_rules.to_csv("./bikeshare/bikeshare_preprocessing_with_rules.csv")